[package]
name = "aoc_2020"
version = "0.1.0"
authors = ["Gianluca Recchia <gianluca.recchia@protonmail.com>"]
edition = "2018"
license = "MIT"
description = "My solutions for AoC 2020"
readme = "README.md"

[profile.release]
lto = "fat"

[dependencies]
clap = "3.0.0-beta.2"
lazy_static = "1.4"
